[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.build]
cmds = ["npm install", "npm run build"]

[phases.install]
cmds = ["npx serve -s build -l $PORT"]

[start]
cmd = "npx serve -s build -l $PORT"

