[phases.setup]
nixPkgs = ["python3", "curl", "tesseract", "poppler_utils"]

[phases.build]
dependsOn = ["setup"]
cmds = [
  "curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py --user",
  "python3 -m pip install --user --upgrade pip setuptools wheel",
  "python3 -m pip install --user -r backend/requirements.txt"
]

[start]
cmd = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

