[phases.setup]
nixPkgs = ["python3", "tesseract", "poppler_utils"]

[phases.build]
dependsOn = ["setup"]
cmds = ["python3 -m ensurepip --upgrade", "python3 -m pip install -r backend/requirements.txt"]

