[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.setuptools", "tesseract", "poppler_utils"]

[phases.build]
dependsOn = ["setup"]
cmds = ["python3 -m pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

