[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "tesseract", "poppler_utils"]

[phases.build]
dependsOn = ["setup"]
cmds = [
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install --upgrade pip",
  "/app/venv/bin/pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && /app/venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

